### ISSUE TITLE
Prepare architecture graph

### ISSUE THREAD

**Issue by marcinlesek** [hypertest-cloud/hypertest#8]

**Comment by blazbla274** [comment]
First scaffold. It's been a while we talked about it last time. So I might not remamber all assumptions we made in first planning. Let's see if this grapth make any sense. ([whimsical source](https://whimsical.com/intrastracture-graph-8JGwK2GYerZR3hivkQEaEZ))

![Image](https://github.com/hypertest-cloud/hypertest/assets/25900361/bdda14d6-8787-4953-9476-6f13cbe373de)

**Comment by marcinlesek** [comment]
@blazbla274 I took a look on the graph, thank you for working on that! I think the best way will be to catch up for a call to talk about it a bit more.
