### ISSUE TITLE
Reasearch Playwright reporters

### ISSUE THREAD

**Issue by blazbla274** [hypertest-cloud/hypertest#9]

**Comment by marcinlesek** [comment]
Playwright allow us to specify reporters via flag in CLI or in Config file.
```bash
npx playwright test --reporter=line
```

```javascript
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: 'line',
});
```

We can also provide array of reporters.

For us, the most important reporters will be:
- [`list`](https://playwright.dev/docs/test-reporters#list-reporter) (default terminal reporter),
- [`html`](https://playwright.dev/docs/test-reporters#html-reporter) (most popular for users),
- [`json`](https://playwright.dev/docs/test-reporters#json-reporter) (most important for us to parse and handle all results).

There is easy way to create [custom reporter](https://playwright.dev/docs/test-reporters#custom-reporters) that will be probably good for us to handle all data.
